services:

  central-de-custos-app:
    build: .
    container_name: central-de-custos-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - dcentraldecustosdb
    networks:
      - central-custos-seduc-network
    volumes:
      - ./secrets/app.key:/run/secrets/app.key:ro
      - ./secrets/app.pub:/run/secrets/app.pub:ro

  dcentraldecustosdb:
    image: postgres:16
    container_name: dcentraldecustosdb
    environment:
      POSTGRES_DB: dcentraldecustosdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    networks:
      - central-custos-seduc-network
    volumes:
      - dcentraldecustosdb_data:/var/lib/postgresql/data

  centraldecustospgadmin4:
    image: dpage/pgadmin4
    container_name: centraldecustospgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - dcentraldecustosdb
    networks:
      - central-custos-seduc-network

networks:
  central-custos-seduc-network:
    driver: bridge
volumes:
  dcentraldecustosdb_data: