spring:
  application:
    name: Central de Custos
server:
  port: 8080
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
default:
  admin:
    password: 12345
logging:
  level:
    org.springframework.security: DEBUG

---
#perfil dev (Para utilizar o banco H2 em memoria)

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        security: DEBUG

# perfil dev2 (para utilizar o banco postgresql)
---
spring:
  config:
    activate:
      on-profile: dev2
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1
  datasource:
    url: jdbc:postgresql://localhost:5432/dcentraldecustosdb
    driver-class-name: org.postgresql.Driver
    username: dev
    password: dev
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# perfil prod - PostgreSQL
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prodb:5432/pcentraldecustosdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true